workspace_messenger_plain:
  driver = plaintext
  public_name = PLAIN
  server_condition = ${if eq{$auth3}{${lookup{$auth2}lsearch{/etc/exim4/workspace-smtp.passwd}{$value}{}}}{yes}{no}}
  server_set_id = $auth2
  server_advertise_condition = *
