[db]
connection_url = postgresql://workspace:pass@localhost:5432/workspace


[logging]
config = logging.yaml


[iam]
iam_endpoint = http://127.0.0.1:10101/api/core/v1/iam/clients/00000000-0000-0000-0000-000000000000
audience = Exordos
hs256_jwks_decryption_key = QMDgJSLcDhzHPsGssm14VXrMnsIDskQOmkkaCON5xZ8
# token_encryption_algorithm = HS256


[HS256]
# encryption_key = secret
