name: Documentation

on:
  pull_request:
    paths:
      - "docs/**"
      - mkdocs.yml
      - pyproject.toml
      - tox.ini
      - uv.lock

permissions:
  contents: read

jobs:
  build_docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - uses: actions/setup-python@v7
        with:
          python-version: "3.12"
      - name: Install system build dependencies
        run: sudo apt update && sudo apt install --yes libev-dev libvirt-dev
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Install tox-uv
        run: uv tool install tox --with tox-uv
      - name: Build docs
        run: tox -e docs-build
